# Generated by Django 5.2.1 on 2025-05-15 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_brand_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="categories",
            new_name="category",
        ),
    ]
