# Generated by Django 5.2.1 on 2025-05-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rename_categories_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=0, max_digits=10, verbose_name="Цена"
            ),
        ),
    ]
