# Generated by Django 5.2.1 on 2025-05-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_category_slug_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
