# Generated by Django 5.2.1 on 2025-05-20 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_category_slug_alter_product_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
    ]
