# Generated by Django 5.2.1 on 2025-05-21 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_remove_category_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="slug",
        ),
    ]
